name: Release

on:
  push:
    tags: ["*@*.*"]

jobs:
  release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: microsoft/setup-msbuild@v2

      - run: nuget restore BetterSort.sln
      - run: msbuild /p:Configuration=Release-1.29.1 BetterSort.sln
      - run: msbuild /p:Configuration=Release-1.34.2 BetterSort.sln
      - run: msbuild /p:Configuration=Release-1.36.2 BetterSort.sln
      - run: msbuild /p:Configuration=Release-1.37.5 BetterSort.sln

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "zip/*.zip"
          draft: true
          skipIfReleaseExists: true
