name: Test

on:
  push:
    branches: [stage]
  pull_request:
    branches: [stage, main]

jobs:
  test:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v2
      - uses: darenm/Setup-VSTest@v1.2

      - run: nuget restore BetterSort.sln
      - run: msbuild /p:Configuration=Release-1.29.1 BetterSort.sln
      - run: msbuild /p:Configuration=Release-1.34.2 BetterSort.sln
      - run: msbuild /p:Configuration=Release-1.36.2 BetterSort.sln
      - run: msbuild /p:Configuration=Release-1.37.5 BetterSort.sln

      - name: Test
        run: >
          vstest.console.exe
          BetterSort.LastPlayed.Test\bin\Release-1.29.1\BetterSort.LastPlayed.Test.dll
          BetterSort.Accuracy.Test\bin\Release-1.29.1\BetterSort.Accuracy.Test.dll
          BetterSort.LastPlayed.Test\bin\Release-1.34.2\BetterSort.LastPlayed.Test.dll
          BetterSort.Accuracy.Test\bin\Release-1.34.2\BetterSort.Accuracy.Test.dll
          BetterSort.LastPlayed.Test\bin\Release-1.36.2\BetterSort.LastPlayed.Test.dll
          BetterSort.Accuracy.Test\bin\Release-1.36.2\BetterSort.Accuracy.Test.dll
          BetterSort.LastPlayed.Test\bin\Release-1.37.5\BetterSort.LastPlayed.Test.dll
          BetterSort.Accuracy.Test\bin\Release-1.37.5\BetterSort.Accuracy.Test.dll
          --TestCaseFilter:"(TestCategory!=NoCi)"
      - name: Push to main
        if: ${{ github.event_name == 'push' }}
        run: |
          git fetch --unshallow origin $(git branch --show-current) main
          git push origin HEAD:main
